### PR TITLE
Option to allow if statement with anything cuddling

### PR DESCRIPTION
**Pull request by pamburus**

### CODE REVIEW

**Comment by bombsimon** [comment]
Thanks for the PR.

I must ask, what's the end goal here? If you allow cuddling assign statements and if statements with anything, it's not much left for this inter to do, is it? Ranges maybe, but that's weird to allow those but not if.

I thought you had some use case with the assign PR (it's never been discussed before so didn't know what). My idea of not cuddling blocks (any blocks) is probably top 3 reasons I made this linter. I'm not sure I follow the reasoning behind this.

So I'm not as eager to merge this as I was with the assign PR and would appreciate you sharing use cases or your code where you feel this is needed but how you're still in line with the linter philosophy.

**Comment by pamburus** [comment]
We want to use WSL for our existing code. But we cannot use it as is because our coding style requirements differ and WSL produces thousands of errors which we do not want to fix in our code.
Primarily we need strict white space control for flow control statements like return, break, continue, etc.
Speaking about if statements, typical go code contains so much if statements that we do not consider that they deserve extra spacing. Adding too much blank lines is another edge of a sword - if there are too much blank lines in the code overall, then return, break, continue and other flow control statements become less visible. But they definitely deserve more attention than if statements.
It is very hard to formalise which if statements are allowed to be cuddled and which are not.
Maybe in the future we could find out more precise requirements for if statements cuddling that we need. But currently it would be enough for our use cases to be able to turn off linter for if statements at all. 

One use case example for this change (multiple assignments before if):
```go
now := time.Now()
timeout := r.options.MaxLongPollTimeout
if !r.deadline.IsZero() && r.deadline.After(now) {
	timeout = r.deadline.Sub(now)
} else {
	r.deadline = now.Add(timeout)
}
```

Another use case example for this change (logging before and after an action):
```go
logging.Info("do some action")
err := someAction.Do(ctx)
if err != nil {
	return err
}
logging.Info("some action done")
```

One more use case example for this change (multiple return value checks):
```go
a, b, err := deduceSomeRange()
if err != nil {
	return err
}
if a < 0 {
	return errors.New("negative range bounds are not allowed")
}
if a > b {
	return errors.New("upper bound must be greater of equal than the lower bound")
}
```

One more use case example for this change (argument assignments before call and checks after call):
```go
force := true
options := &Options{
	Option1: "value1",
	Option2: "value2",
}
err := action.Do(force, options)
if err != nil {
	return nil, err
}
```
In our opinion, these things look better when cuddled.
Some users may want use WSL as is, and some of them may want use only selected features.

So, it would be great if WSL could have a switch option for any of the error types it produces.

**Comment by bombsimon** [comment]
Thank you very much for the great answer, really detailed!

I haven't really thought about it that way but I think a lot of thins you say make sense. Especially the idea to just separata flow control statements for easier readability. This linter got started as a joke on leading and trailing whitespaces in blocks so it has definitely grown a lot.

What you say makes me think of an alternative implementation. If people actually like this linter, or the idea of separating **some** of their code, but not all of it, would an alternative be to configure lists (whitelist or blacklist) of statements? One example would be `--enforce branch,return,defer` or `--allow if,assign,declare` and that way you can toggle any kind of statement. The statements should be documented but if they just follow how the AST looks I think it will be OK.

There's also combined configurations today, such as when to force a newline in a case block. That flag makes it possible to force newlines for cases more than `n` lines. A similar thing would probably be useful for if statements, e.g. enforce newline after an if statement that's more than 10 lines or more than 3 statements or whatever sounds reasonable.

I think this will give more control to the user but also reduce the number of parameters. I want to take this in consideration both for the linter itself, but also to not clog the [`golangci-lint` config](https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml#L271-L289) too much (I think we're already the linter with most example configuration).

**Comment by bombsimon** [comment]
The goal for this PR seemed to be to turn of all warnings but `return` statements. I never got any feedback regarding my proposal but I think I'll close this one and open an issue regarding better allow-/blocklist.

A new linter called [nlreturn](https://github.com/ssgreg/nlreturn) has been created and is merged ot [golangci-lint](https://github.com/golangci/golangci-lint) where the PR also mentioned this specific PR.

**Comment by bombsimon** [comment]
@pamburus Hello almost 6 years later! I don't know if you still write Go or if this is something you care about, but a while back `wsl` v5 was released with support for this. It's now possible to enabler or disable any specific check.

**Pull request closed without merging**
