### PR TITLE
test: fix cgo tests

### PR DESCRIPTION
**Pull request by ldez**
related to https://github.com/bombsimon/wsl/pull/157

### CODE REVIEW

**Comment by bombsimon** [comment]
Thanks @ldez!

Is this ready to merge or are more changes needed?

**Comment by ldez** [comment]
This is ready to merge

**Comment by bombsimon** [comment]
> This is ready to merge

Perfect, thanks for this! Anything to add before I make a new release?

**Comment by ldez** [comment]
You can release, now there is tests :smile_cat:

**Pull request merged**
