### PR TITLE
Skip analysis of generated files

### PR DESCRIPTION
**Pull request by kseniadumpling**
Hi! I have a suggestion to make, hope you don't mind :)
Since `golangci-lint` doesn't support SuggestedFixes (https://github.com/golangci/golangci-lint/issues/1779), in my project I call `wsl --fix` separately. And it turns out that the linter fixes everything, including generated files (for example, files that are generated by protoc-gen-go). 
This PR suggest to skip such files. It uses `ast.IsGenerated(file *ast.File)` as recommended in https://github.com/golang/go/issues/43481 and https://github.com/golang/go/issues/28089

### CODE REVIEW

**Comment by bombsimon** [comment]
Thanks! I think this makes sense! Either you're not in control of the generator and can't do anything about it or you are and should fix the generator. Since generated files usually shouldn't be edited I can't think of a reason to not do this or make it an opt-in and just always ignore them.

I'll merge this and if someone really want's to fix generated files we can add a flag in the future.

**Comment by kseniadumpling** [comment]
@bombsimon sure!
rebased 👌🏻

**Comment by kseniadumpling** [comment]
Hi @bombsimon
Sorry to bother you, but is there any chance of seeing this change in the tagged version? :)

**Comment by bombsimon** [comment]
> Hi @bombsimon Sorry to bother you, but is there any chance of seeing this change in the tagged version? :)

Not at all, thanks for the ping and patiently waiting! This was a miss by me, I've tagged [v4.3.0](https://github.com/bombsimon/wsl/releases/tag/v4.3.0) with this change included. Hope that helps!

**Comment by kseniadumpling** [comment]
Yep, thanks a lot!

**Comment by ldez** [comment]
First, I agree with skipping generated files, but there is a missing case here: when you work on a generator.

When you work on a generator, you try to generate "right" files.

I think should be an option.

**Comment by bombsimon** [comment]
> First, I agree with skipping generated files, but there is a missing case here: when you work on a generator.
> 
> When you work on a generator, you try to generate "right" files, so you need linters.
> 
> I think it should be an option.

Thanks for your input!

To me this feels like a rare edge case. I think this is reasonable for linters that check for bugs or security issues but for styling it makes less sense since you're likely not going to read (and never change) generated code.

Although not an optimal flow, a workaround if you're the author of the generator and want the code to be linted could be to simply avoid adding the `Code generated` comment and it will be picked up.

I can add a flag for it. If so, do you think it makes sense to ignore generated code by default?

**Pull request merged**
